In [17]:
import os
import scipy
import tifffile
import numpy as np
import pandas as pd

folder_path = '/Users/domchom/Desktop'

# Load image
images = {}

for filename in os.listdir(folder_path):
    if filename.endswith('.tif'):
        filename_path = os.path.join(folder_path, filename)

        image = tifffile.imread(filename_path)

        # standardize image dimensions
        with tifffile.TiffFile(filename_path) as tif_file:
            metadata = tif_file.imagej_metadata
        num_channels = metadata.get('channels', 1)
        num_slices = metadata.get('slices', 1)
        num_frames = metadata.get('frames', 1)
        image = image.reshape(num_frames,
                                num_slices,
                                num_channels, 
                                image.shape[-1],  # columns
                                image.shape[-2])  # rows

        images[filename_path] = image
   

window_range = range(5,50,1)

for image in images:
    max_variance = -1
    for i in window_range:
        result = abs(scipy.ndimage.uniform_filter(images[image]**2, size=i, output=np.float64) - 
                    (scipy.ndimage.uniform_filter(images[image], size=i, output=np.float64)**2))
        variance = result.max()
        if variance > max_variance:
            max_variance = variance
            size = i

print(size)
print(max_variance)

[[[[[ 358  958  894 ...  858  936  988]
    [ 821  926  582 ... 1025  681  898]
    [ 913 1162 1180 ...  912 1090  683]
    ...
    [ 972  642  910 ...  794  920  598]
    [ 694  543  417 ... 1020  621  554]
    [1011  606  688 ...  772  624  776]]]]]
5
1874714.2400000058


In [18]:
import os
import scipy
import tifffile
import numpy as np
import pandas as pd

folder_path = '/Users/domchom/Desktop'

# Load image
images = {}

for filename in os.listdir(folder_path):
    if filename.endswith('.tif'):
        filename_path = os.path.join(folder_path, filename)

        image = tifffile.imread(filename_path)

        # standardize image dimensions
        with tifffile.TiffFile(filename_path) as tif_file:
            metadata = tif_file.imagej_metadata
        num_channels = metadata.get('channels', 1)
        num_slices = metadata.get('slices', 1)
        num_frames = metadata.get('frames', 1)
        image = image.reshape(num_frames,
                                num_slices,
                                num_channels, 
                                image.shape[-1],  # columns
                                image.shape[-2])  # rows

        images[filename_path] = image
   

window_range = range(5,50,1)

for image in images:
    maxvar_dic = {}
    for i in window_range:
        result = abs(scipy.ndimage.uniform_filter(images[image]**2, size=i, output=np.float64)-(scipy.ndimage.uniform_filter(images[image], size=i, output=np.float64)**2))
        maxvar_dic[i] = {}
        maxvar_dic[i]["window_size"] = i
        maxvar_dic[i]["max_variance"] = result.max()
    df = pd.DataFrame(data=maxvar_dic)
    df = df.transpose()
    max_size= int(df["window_size"].loc[df["max_variance"] == df["max_variance"].max()])
    size = max_size

print(size)
print(maxvar_dic)

5
{5: {'window_size': 5, 'max_variance': 1874714.2400000058}, 6: {'window_size': 6, 'max_variance': 1774272.7222222232}, 7: {'window_size': 7, 'max_variance': 1693717.785922534}, 8: {'window_size': 8, 'max_variance': 1667167.9338378906}, 9: {'window_size': 9, 'max_variance': 1597232.4157902754}, 10: {'window_size': 10, 'max_variance': 1521698.747600003}, 11: {'window_size': 11, 'max_variance': 1465245.4367871108}, 12: {'window_size': 12, 'max_variance': 1415545.9878472239}, 13: {'window_size': 13, 'max_variance': 1375721.250306363}, 14: {'window_size': 14, 'max_variance': 1340663.7835537288}, 15: {'window_size': 15, 'max_variance': 1300930.3397530841}, 16: {'window_size': 16, 'max_variance': 1303055.0451660156}, 17: {'window_size': 17, 'max_variance': 1295921.2344679823}, 18: {'window_size': 18, 'max_variance': 1264967.583257127}, 19: {'window_size': 19, 'max_variance': 1248696.4947168936}, 20: {'window_size': 20, 'max_variance': 1237186.4152250038}, 21: {'window_size': 21, 'max_varian